{MENU}
<br />
<!-- BEGIN MSG -->
<b>{MSG}</b><br /><br />
<!-- END MSG -->
{FORM}
<!-- BEGIN BOX -->
{BOX_HELP}{BOX_LABEL}?: {BOX_YES} {BOX_NO}<br />
<!-- END BOX -->
<!-- BEGIN FOOTER -->
{FOOTER_HELP}{FOOTER_LABEL}: {FOOTER_YES} {FOOTER_NO}<br />
<!-- END FOOTER -->
<!-- BEGIN USERSEND -->
{USERSEND_HELP}{USERSEND_LABEL}: {USERSEND_YES_NA} {USERSEND_YES_WA} {USERSEND_NO}<br />
<!-- END USERSEND -->
<!-- BEGIN ANONSUBSCRIBE -->
{ANONSUBSCRIBE_HELP}{ANONSUBSCRIBE_LABEL}: {ANONSUBSCRIBE_YES} {ANONSUBSCRIBE_NO}<br />
<!-- END ANONSUBSCRIBE -->
<!-- BEGIN SUBJECTPREFIX -->
{SUBJECTPREFIX_HELP}{SUBJECTPREFIX_LABEL}: {SUBJECTPREFIX_YES} {SUBJECTPREFIX_NO}<br />
<!-- END SUBJECTPREFIX -->
<!-- BEGIN FOOTHTML -->
<br />{FOOTHTML_HELP}{FOOTHTML_LABEL}:<br />{FOOTHTML}<br />
<!-- END FOOTHTML -->
<!-- BEGIN CONVERT_BUTTON -->
<br />{CONVERT_HELP}{CONVERT_BUTTON}<br />
<!-- END CONVERT_BUTTON -->
<!-- BEGIN FOOTPLAIN -->
<br />{FOOTPLAIN_HELP}{FOOTPLAIN_LABEL}:<br />{FOOTPLAIN}<br />
<!-- END FOOTPLAIN -->
<!-- BEGIN SUBMIT -->
<br />{SUBMIT_BUTTON}
<!-- END SUBMIT -->
{END_FORM}
